// auto-generated by gen_workflows.py, DO NOT EDIT
#include "workflows_gen.h"
#include "result_code.h"
#include <stddef.h>

/* === step / condition externs === */
extern StepRet step_init(WorkflowContext *t, void *m, WORD32 l, StepContext *ctx);
extern StepRet step_select_handler(WorkflowContext *t, void *m, WORD32 l, StepContext *ctx);
extern StepRet step_respond(WorkflowContext *t, void *m, WORD32 l, StepContext *ctx);
extern StepRet step_cleanup(WorkflowContext *t, void *m, WORD32 l, StepContext *ctx);
extern StepRet step_process_data(WorkflowContext *t, void *m, WORD32 l, StepContext *ctx);
extern int cond_isComplete(WorkflowContext *t, void *m, WORD32 l, StepContext *ctx);

/* ============================================================
 * Workflow: SimpleFlow
 * ============================================================ */

/* state index macros */
#define IDX_SimpleFlow_init  0
#define IDX_SimpleFlow_select_handler  1
#define IDX_SimpleFlow_process_data  2
#define IDX_SimpleFlow_respond  3
#define IDX_SimpleFlow_while_isComplete  4
#define IDX_SimpleFlow_cleanup  5

/* control-flow wrappers */
static StepRet wrapper_SimpleFlow_while_isComplete(WorkflowContext *t, void *m, WORD32 l, StepContext *ctx)
{
    if (!cond_isComplete(t, m, l, ctx))
        ctx->nextIdx = IDX_SimpleFlow_process_data;
    return STEP_RET_OK;
}

/* 旧 goto 解释器。新 stepRun 只跑 Instance 指令表，这里留给尚未重生成的 workflows_gen。 */
static void legacyStepRun(void *workflow, void *msg, WORD32 len)
{
    WorkflowContext *t = (WorkflowContext *)workflow;
    StepContext *ctx = &t->step;
    StateEntry *table = t->stateTable;

    while (1) {
        StateEntry *entry = &table[ctx->idx];
        if (!entry->func) {
            return;
        }

        ctx->nextIdx = ctx->idx + 1;
        StepRet ret = (StepRet)entry->func(workflow, msg, len, ctx);

        switch (ret) {
        case STEP_RET_OK:
            ctx->idx = ctx->nextIdx;
            continue;
        case STEP_RET_WAIT:
        case STEP_RET_END:
        case STEP_RET_FAIL:
            return;
        default:
            return;
        }
    }
}

/* state table */
static StateEntry st_SimpleFlow[] = {
{ (LegacyStepFn)step_init, "init" },
{ (LegacyStepFn)step_select_handler, "select_handler" },
{ (LegacyStepFn)step_process_data, "process_data" },
{ (LegacyStepFn)step_respond, "respond" },
{ (LegacyStepFn)wrapper_SimpleFlow_while_isComplete, "while_isComplete" },
{ (LegacyStepFn)step_cleanup, "cleanup" },
{ NULL, NULL }
};

/* entry */
RetCode workflow_SimpleFlow(WorkflowContext *t, void *m, WORD32 l)
{
    t->stateTable = st_SimpleFlow;
    t->step.idx = 0;
    t->step.nextIdx = 0;
    legacyStepRun(t, m, l);
    return RC_SUCCESS;
}

/* resume */
void SimpleFlow_resume(WorkflowContext *t, void *m, WORD32 l)
{
    legacyStepRun(t, m, l);
}


/* ============================================================
 * Action → Workflow mapping tables
 * ============================================================ */
const WorkflowFunc g_workflow_table[] = {
[ACTION_SIMPLE_A] = workflow_SimpleFlow,
[ACTION_SIMPLE_B] = workflow_SimpleFlow,
};

const WorkflowResumeFunc g_workflow_resume_table[] = {
[ACTION_SIMPLE_A] = SimpleFlow_resume,
[ACTION_SIMPLE_B] = SimpleFlow_resume,
};

const WORD32 g_workflow_table_size = sizeof(g_workflow_table) / sizeof(g_workflow_table[0]);
